"""empty message

Revision ID: 47156925c666
Revises: 
Create Date: 2021-08-31 23:58:44.152744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47156925c666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customer', 'user', ['user_id'], ['id'])
    op.add_column('modifications', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('modifications', sa.Column('modified_by', sa.Integer(), nullable=False))
    op.add_column('modifications', sa.Column('modification_date', sa.DateTime(), nullable=True))
    op.drop_constraint('modifications_user_id_fkey', 'modifications', type_='foreignkey')
    op.create_foreign_key(None, 'modifications', 'user', ['modified_by'], ['id'])
    op.drop_column('modifications', 'modified_at')
    op.drop_column('modifications', 'user_id')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_admin')
    op.add_column('modifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modifications', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modifications', type_='foreignkey')
    op.create_foreign_key('modifications_user_id_fkey', 'modifications', 'user', ['user_id'], ['id'])
    op.drop_column('modifications', 'modification_date')
    op.drop_column('modifications', 'modified_by')
    op.drop_column('modifications', 'id')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'user_id')
    # ### end Alembic commands ###
