"""empty message

Revision ID: 4ee8a30dc551
Revises: 28d9b1832a08
Create Date: 2021-08-30 01:48:27.516962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee8a30dc551'
down_revision = '28d9b1832a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
