"""empty message

Revision ID: 50e3c5c9f865
Revises: 4ee8a30dc551
Create Date: 2021-08-30 22:06:26.939769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e3c5c9f865'
down_revision = '4ee8a30dc551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
