"""empty message

Revision ID: 5d854204202c
Revises: 082f9f5c6854
Create Date: 2021-08-31 12:48:24.180783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d854204202c'
down_revision = '082f9f5c6854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
