"""empty message

Revision ID: 65fe688a796e
Revises: 8f326b785e6d
Create Date: 2021-08-28 13:42:04.545526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fe688a796e'
down_revision = '8f326b785e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
