"""empty message

Revision ID: 8f326b785e6d
Revises: bd157b662087
Create Date: 2021-08-28 13:37:41.206568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f326b785e6d'
down_revision = 'bd157b662087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
