"""empty message

Revision ID: a0a32f75e9f7
Revises: b681d0ba7a05
Create Date: 2021-08-29 23:41:51.874615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a32f75e9f7'
down_revision = 'b681d0ba7a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
