"""empty message

Revision ID: a168a080c461
Revises: a0a32f75e9f7
Create Date: 2021-08-29 23:56:27.075821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a168a080c461'
down_revision = 'a0a32f75e9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
