"""empty message

Revision ID: b681d0ba7a05
Revises: 27ba512f735e
Create Date: 2021-08-29 20:01:17.720425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b681d0ba7a05'
down_revision = '27ba512f735e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_name_creator', sa.String(length=20), nullable=False))
    op.alter_column('customers', 'avatar_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'avatar_url',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('customers', 'user_name_creator')
    # ### end Alembic commands ###
