"""empty message

Revision ID: bd157b662087
Revises: f05dd82e9291
Create Date: 2021-08-28 12:48:03.589422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd157b662087'
down_revision = 'f05dd82e9291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
