"""empty message

Revision ID: c89bf0477b82
Revises: 65fe688a796e
Create Date: 2021-08-28 13:52:05.113918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89bf0477b82'
down_revision = '65fe688a796e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
