"""empty message

Revision ID: cab398b94e92
Revises: c89bf0477b82
Create Date: 2021-08-28 17:06:35.964830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab398b94e92'
down_revision = 'c89bf0477b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
