"""empty message

Revision ID: f05dd82e9291
Revises: fb0afdc575a1
Create Date: 2021-08-28 12:10:33.644744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05dd82e9291'
down_revision = 'fb0afdc575a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
